### ISSUE TITLE
assertion failure in async-coap/src/datagram/send_future.rs:275

### ISSUE THREAD

**Issue by aav** [google/rust-async-coap#20]
handle_response() should only be called when self.state().is_waiting() == true.

**Comment by aav** [comment]
In my environment, I can observe, that sometimes UDP response from coap.me/separate arrives several times. As I can see with Wireshark, in cases local endpoint receives 2 or even 3 similar looking CoAP messages with same token. 

In such a case, the first one is handled properly, but when the subsequent one, reaches handle_response(), the assertion fails.

**Comment by aav** [comment]
It looks like the UDP ResponseTracer does not remove "old" tokens when a response is matched on a token, and not on message-id. Problematic code is located around async-coap/src/datagram/response_tracker.rs:81.

**Comment by darconeous** [comment]
It is generally acceptable to receive several response messages with the same token. Indeed, this ability is required to receive multiple multicast responses and for observing... But clearly there is still a bug here.

You are right that the handler should be removed from the tracker, but this shouldn't be assumed by the tracker—`remove_response_handler` needs to be called by the `SendFuture` when it is finished. In the existing code, that happens on line 475 of `send_future.rs`:

https://github.com/google/rust-async-coap/blob/master/async-coap/src/datagram/send_future.rs#L474-L476

But this clearly isn't good enough, as evidenced by you hitting the assert.

So I see two options: 

1. Instead of asserting if we aren't waiting, just return `Err(Error::Unspecified)` or `Err(Error::Reset)`. The idea here is that we are trusting that `drop()` will eventually be called on the future and clean things up properly then.
2. Somehow ensure that `remove_response_handler` gets called earlier.

\#2 might seem like the ideal solution, but if we just do this naively (like calling it directly on the state transition) we deadlock because the mutex is already being held.

Perhaps the best solution would be to add a boolean return value to the method `HandleResponse::handle_response` that indicates if the handler can handle additional packets or not. Then we could check that return value and remove the entries directly from `UdpResponseTracker::handle_response` implementation.

Thoughts?

**Comment by aav** [comment]
I will take a deeper look next days and reply with my thoughts. This week I've been away and had almost no time to work. :(

**Comment by aav** [comment]
Sorry for the long silence. I agree that the second option is better. Will make a prototype and update the pull request.

**Comment by aav** [comment]
The pull request is updated, according to the second option.

**Comment by darconeous** [comment]
sorry for the delay. Having a look at the new changes.
